package org.project.models;

public enum PacketType {
    SIGN_UP,
    LOGIN,
    LOGOUT,
    SEND_MESSAGE,
    SEND_GROUP_MESSAGE,
    SEND_CHANNEL_MESSAGE,
    NEW_MESSAGE,
    MESSAGE_STATUS_UPDATE,
    CREATE_GROUP,
    ADD_GROUP_MEMBER,
    CREATE_CHANNEL,
    ADD_CHANNEL_MEMBER,
    VIEW_PROFILE,
    UPDATE_PROFILE,
    CHANGE_PASSWORD,
    FETCH_CHATS,
    CHATS_LIST,
    FETCH_CHAT_HISTORY,
    MESSAGES_LIST,
    TYPING,
    SEARCH_USER,
    SEARCH_RESULTS,
    USER_ONLINE,
    USER_OFFLINE,
    ONLINE_USERS_LIST,
    MARK_AS_READ,
    ERROR,
    SUCCESS,

    // انواع جدید اضافه شده
    ADD_MEMBER,
    FETCH_MEMBERS,
    MEMBERS_LIST
}